Add docker-compose deployments for all supported blockchains until no…
pokt-network/pocket-core-deployments pull request #13
Opened 2019-06-29 04:03 UTC by aqt01

- Add docker-compose for all blockchains supported by pocket-core
- Add minimal docks on how to run them
- Adds nginx as additional container for using proxy
- Not recommended for running in production, needs some improvements, but its a great tool for testing all of them

2019-07-01 17:24 UTC, luyzdeleon requested changes
The directory structure for this is wrong, we need to have the deployment artifact platform as the root folder:

dappnode
docker
docker-compose
etc...

2019-07-01 23:02 UTC, luyzdeleon requested changes
Can we add to the top of every docker-compose file what is being installed and how to configure it?

2019-07-01 23:02 UTC, luyzdeleon commented on docker-compose/README.md
> +# Pocket-core docker-compose
Can this README follow the same format as here: https://github.com/pokt-network/pocket-core-deployments/blob/mvp-master/dappnode/README.md

And just link to the developer portal here: https://docs.pokt.network/docs/docker-service-node-setup

2019-07-01 23:02 UTC, luyzdeleon commented on docker-compose/aion/aion-mastery/Dockerfile
> +FROM aionnetwork/aionr:Latest
Is there a typo on `Latest`, should it be `latest`?

2019-07-01 23:02 UTC, luyzdeleon commented on docker-compose/all/docker-compose.yml
> +version: '3'
Can we add a comment at the top of the file indicating which networks are included in `all`?

2019-07-01 23:02 UTC, luyzdeleon commented on docker-compose/nginx/Dockerfile
> +FROM alpine:3.9
Can we explain either in the README or in this same file why we need nginx? Whether is required or optional?

2019-07-04 20:10 UTC, luyzdeleon submitted a review, later dismissed

2019-11-26 23:43 UTC, edjroz commented on docker-compose/lightchain/Dockerfile
> +MAINTAINER Gabriel Garrido
The `MANTAINER` keyword for docker files has been marked as [deprecated](https://docs.docker.com/engine/reference/builder/) and should likely be replaced by `LABEL`

2019-11-27 21:58 UTC, nelcolon submitted a review, later dismissed

2019-11-28 13:04 UTC, edjroz submitted a review, later dismissed

2019-12-09 19:06 UTC, nelcolon reviewed
Should be fine.

2019-12-09 19:07 UTC, nelcolon approved these changes

2019-12-09 19:14 UTC, merged